### ISSUE TITLE
謝謝你的心得作業

### ISSUE THREAD

**Issue by azole** [TaylorLiu11/git-workshop#2]
謝謝你的心得作業，練習整理資訊是非常重要的練習，你做得很棒，最喜歡你整理的這句

> 這太難了我沒有天分，學不會啦 → 這感覺很難，但我只是還沒學會

一個角度轉換，整個心態都不一樣了，如果能繼續保持這種心態，那會非常適合在工程師這條路走下去的。

**Comment by TaylorLiu11** [comment]
感謝老師！會繼續保持的😄
